# User Service开发环境配置

server:
  port: 8001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@localhost:8761/eureka/

# 业务配置
user:
  jwt:
    secret: user-service-jwt-secret-key-2024
    expiration: 86400000  # 24小时
