apiVersion: v1
kind: Service
metadata:
  name: $APP_NAME
  namespace: yfz-test-env-ns
spec:
  selector:
    app: $APP_NAME
  ports:
    - name: http
      port: 9990
      targetPort: 9990
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: $APP_NAME
  namespace: yfz-test-env-ns
spec:
  replicas: 1
  minReadySeconds: 1
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  selector:
    matchLabels:
      app: $APP_NAME
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: $APP_NAME
    spec:
      containers:
        - name: $APP_NAME
          image: $REGISTRY/$DOCKERREGISTRY_NAMESPACE/$APP_NAME:$BRANCH-$BUILD_NUMBER
          ports:
            - containerPort: 9990
              protocol: TCP
          volumeMounts:
            - name: yfz-test-log-pv
              mountPath: /mnt
          #readinessProbe:
            #httpGet:
              #path: /actuator/info
              #port: 9990
            #initialDelaySeconds: 1
            #periodSeconds: 5
          resources:
            limits:
              cpu: '2'
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      volumes:
        - name: yfz-test-log-pv
          persistentVolumeClaim:
            claimName: yfz-test-log-pvc
            readOnly: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
